import = [
	"~/.config/alacritty/themes/themes/cyber_punk_neon.toml"
]

[font]
size = 10.0

[font.bold]
family = "Share Tech Mono"
style = "Bold"

[font.bold_italic]
family = "Share Tech Mono"
style = "Bold Italic"

[font.italic]
family = "Share Tech Mono"
style = "Italic"

[font.normal]
family = "Share Tech Mono"
style = "Regular"
